trigger:
  - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Pre
    jobs:
      - job: PreTest
        steps:
          - script: echo "Pre test script"
      - job: Pre_Test_2
        steps:
          - script: echo "Another job run"    

  - stage: Test
    jobs:
      - job: TestWork
        strategy:
          matrix:
            demo:
              fileName: 'demo-todo-app.spec.ts'
            example1:
              fileName: 'example.spec.ts'
            example2:
              fileName: 'example2.spec.ts'

        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Install Node.js'
          - script: |
              npm install
              npx playwright install --with-deps
            displayName:  'Install npm deps'
          - script: npm test -- $(fileName)


  - stage: Post
    jobs:
      - job: PostTest
        steps:
          - script: echo "Post test script"
