variables:
  npm_config_cache: $(Pipeline.Workspace)/.npm

trigger:
  - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Pre
    jobs:
      - job: PreTest
        steps:
          - script: echo "Pre test script"
          - script: echo "##vso[task.setvariable variable=testVar1;isOutput=true]value"
            name: Pre_one
      - job: Pre_Test_2
        steps:
          - script: echo "Another job run"    
          - script: echo "##vso[task.setvariable variable=testVar2;isOutput=true]other"
            name: Pre_two

  - stage: Post
    dependsOn: [Pre]
    variables:
      one: $[stageDependencies.Pre.PreTest.outputs['Pre_one.testVar1']]
      two: $[stageDependencies.Pre.Pre_Test_2.outputs['Pre_two.testVar2']]
    jobs:
      - job: PostTest
        steps:
          - script: echo "first var - $TEST_VAR"
            env:
              TEST_VAR: $(one)
          - script: echo "second var - $TEST_VAR"
            env:
              TEST_VAR: $(two)
          - script: echo "first var env exp - $TEST_VAR"
            env:
              TEST_VAR: $[stageDependencies.Pre.PreTest.outputs['Pre_one.testVar1']]
          - script: echo "second var env exp - $TEST_VAR"
            env:
              TEST_VAR: $[stageDependencies.Pre.Pre_Test_2.outputs['Pre_two.testVar2']]
